export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'lg', name: 'Luganda', nativeName: 'Oluganda', flag: '🇺🇬' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', flag: '🇪🇹' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', flag: '🇿🇦' },
  { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo', flag: '🇳🇬' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', flag: '🇸🇴' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', flag: '🇿🇦' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'tl', name: 'Tagalog', nativeName: 'Tagalog', flag: '🇵🇭' },
];

// UI Localizations Dictionary
export const UI_DICTIONARY: Record<string, Record<string, string>> = {
  en: {
    chats: 'Chats',
    groups: 'Groups',
    channels: 'Channels',
    communities: 'Communities',
    mail: 'Mail',
    stories: 'Stories',
    settings: 'Settings',
    search: 'Search...',
    typeMessage: 'Type a message...',
    savedMessages: 'Saved Messages',
    interfaceLanguage: 'App Interface Language',
    translationTarget: 'Translation Target Language',
    searchLanguage: 'Search language...',
    autoTranslate: 'Auto-Translate Incoming Messages',
    autoTranslateDesc: 'Automatically translate incoming messages to your preferred language',
    online: 'online',
    offline: 'offline',
    translating: 'Translating...',
    showOriginal: 'Show Original',
    showTranslation: 'Show Translation',
    editProfile: 'Edit Profile',
    notifications: 'Notifications & Sounds',
    privacy: 'Privacy & Security',
    language: 'Language & Translation',
    appearance: 'Appearance & Themes',
    storage: 'Data & Storage',
    devices: 'Devices & Sessions',
    help: 'Help & FAQ',
    myAccount: 'My Account',
    general: 'General',
    account: 'Account',
    inbox: 'Inbox',
    sent: 'Sent',
    drafts: 'Drafts',
    trash: 'Trash',
    starred: 'Starred',
    archive: 'Archive',
    newChat: 'New Chat',
    newGroup: 'New Group',
    newChannel: 'New Channel',
    newMail: 'Compose Mail',
    voiceCall: 'Voice Call',
    videoCall: 'Video Call',
    languageSettingsDesc: 'Choose your interface display language and message translation settings.',
  },
  lg: { // Luganda
    chats: 'Amawulire',
    groups: 'Ebipindi',
    channels: 'Kyenaku',
    communities: 'Akitundu',
    mail: 'Ebaruwa',
    stories: 'Ebyafaayo',
    settings: 'Enteekateeka',
    search: 'Noonya...',
    typeMessage: 'Wandiika obubaka...',
    savedMessages: 'Obubaka Obutereke',
    interfaceLanguage: 'Olulimi lw\'Akakiiko',
    translationTarget: 'Olulimi Oluvuunulwa',
    searchLanguage: 'Noonya olulimi...',
    autoTranslate: 'Okwetongola mu Kuvuunula',
    autoTranslateDesc: 'Vuunula obubaka bwonna obujja mu lulimi lwo',
    online: 'ali ku mutimbagano',
    offline: 'tali ku mutimbagano',
    translating: 'Okuvuunula...',
    showOriginal: 'Laga Ekyasooka',
    showTranslation: 'Laga Ekyavuunulwa',
    editProfile: 'Kyusa Ebifa ku Yowwe',
    notifications: 'Abeeyagaza & Amaloboozi',
    privacy: 'Ebyama & Obukuumi',
    language: 'Olulimi & Okuvuunula',
    appearance: 'Endabika & Emisono',
    storage: 'Ebiwandiiko & Ebyetereko',
    devices: 'Ebyuma & Obuyungiro',
    help: 'Obuyambi & Ebibuzo',
    myAccount: 'Akaunti Yange',
    general: 'Ebyawamu',
    account: 'Akaunti',
    inbox: 'Ebijja',
    sent: 'Ebiweerezeddwa',
    drafts: 'Ebitagattidwa',
    trash: 'Esubi',
    starred: 'Ebirondemu',
    archive: 'Ebitereke',
    newChat: 'Amawulire Omapya',
    newGroup: 'Ekipindi Ekipya',
    newChannel: 'Kyenaku Ekipya',
    newMail: 'Wandiika Ebaruwa',
    voiceCall: 'Okukuba Isimu',
    videoCall: 'Isimu y\'Edifaananyi',
    languageSettingsDesc: 'Londa olulimi lw\'endabika ne nteekateeka z\'okuvuunula obubaka.',
  },
  sw: { // Swahili
    chats: 'Soga',
    groups: 'Vikundi',
    channels: 'Vituo',
    communities: 'Jumuia',
    mail: 'Barua',
    stories: 'Hadithi',
    settings: 'Mipangilio',
    search: 'Tafuta...',
    typeMessage: 'Andika ujumbe...',
    savedMessages: 'Ujumbe Uliowekwa',
    interfaceLanguage: 'Lugha ya Programu',
    translationTarget: 'Lugha ya Tafsiri',
    searchLanguage: 'Tafuta lugha...',
    autoTranslate: 'Tafsiri Ujumbe Otomatiki',
    autoTranslateDesc: 'Tafsiri ujumbe unaoingia kwa lugha yako unayoipenda kiotomatiki',
    online: 'yuko mtandaoni',
    offline: 'hayuko mtandaoni',
    translating: 'Inatafsiri...',
    showOriginal: 'Onyesha Halisi',
    showTranslation: 'Onyesha Tafsiri',
    editProfile: 'Hariri Profaili',
    notifications: 'Arifa na Sauti',
    privacy: 'Faragha na Usalama',
    language: 'Lugha na Tafsiri',
    appearance: 'Muonekano na Mandhari',
    storage: 'Data na Hifadhi',
    devices: 'Vifaa na Siku',
    help: 'Msaada na Maswali',
    myAccount: 'Akaunti Yangu',
    general: 'Jumla',
    account: 'Akaunti',
    inbox: 'Sanduku la Inbound',
    sent: 'Zilizotumwa',
    drafts: 'Kraschlandning',
    trash: 'Takataka',
    starred: 'Zilizowekwa Nyota',
    archive: 'Kumbukumbu',
    newChat: 'Soga Mpya',
    newGroup: 'Kikundi Kipya',
    newChannel: 'Kituo Kipya',
    newMail: 'Andika Barua',
    voiceCall: 'Piga Simu',
    videoCall: 'Simu ya Video',
    languageSettingsDesc: 'Chagua lugha ya muonekano na mipangilio ya tafsiri ya ujumbe.',
  },
  es: { // Spanish
    chats: 'Chats',
    groups: 'Grupos',
    channels: 'Canales',
    communities: 'Comunidades',
    mail: 'Correo',
    stories: 'Historias',
    settings: 'Ajustes',
    search: 'Buscar...',
    typeMessage: 'Escribe un mensaje...',
    savedMessages: 'Mensajes Guardados',
    interfaceLanguage: 'Idioma de la Aplicación',
    translationTarget: 'Idioma Destino de Traducción',
    searchLanguage: 'Buscar idioma...',
    autoTranslate: 'Traducir Mensajes Automáticamente',
    autoTranslateDesc: 'Traduce automáticamente los mensajes entrantes a tu idioma preferido',
    online: 'en línea',
    offline: 'desconectado',
    translating: 'Traduciendo...',
    showOriginal: 'Ver Original',
    showTranslation: 'Ver Traducción',
    editProfile: 'Editar Perfil',
    notifications: 'Notificaciones y Sonidos',
    privacy: 'Privacidad y Seguridad',
    language: 'Idioma y Traducción',
    appearance: 'Apariencia y Temas',
    storage: 'Datos y Almacenamiento',
    devices: 'Dispositivos y Sesiones',
    help: 'Ayuda y Preguntas',
    myAccount: 'Mi Cuenta',
    general: 'General',
    account: 'Cuenta',
    inbox: 'Bandeja de Entrada',
    sent: 'Enviados',
    drafts: 'Borradores',
    trash: 'Papelera',
    starred: 'Destacados',
    archive: 'Archivados',
    newChat: 'Nuevo Chat',
    newGroup: 'Nuevo Grupo',
    newChannel: 'Nuevo Canal',
    newMail: 'Redactar Correo',
    voiceCall: 'Llamada de Voz',
    videoCall: 'Videollamada',
    languageSettingsDesc: 'Selecciona el idioma de la interfaz y la configuración de traducción de mensajes.',
  },
  fr: { // French
    chats: 'Discussions',
    groups: 'Groupes',
    channels: 'Chaînes',
    communities: 'Communautés',
    mail: 'Courrier',
    stories: 'Stories',
    settings: 'Paramètres',
    search: 'Rechercher...',
    typeMessage: 'Écrivez un message...',
    savedMessages: 'Messages Enregistrés',
    interfaceLanguage: 'Langue de l\'Interface',
    translationTarget: 'Langue de Traduction Cible',
    searchLanguage: 'Rechercher une langue...',
    autoTranslate: 'Traduire Automatiquement les Messages',
    autoTranslateDesc: 'Traduire automatiquement les messages entrants dans votre langue',
    online: 'en ligne',
    offline: 'hors ligne',
    translating: 'Traduction...',
    showOriginal: 'Voir l\'original',
    showTranslation: 'Voir la traduction',
    editProfile: 'Modifier le Profil',
    notifications: 'Notifications & Sons',
    privacy: 'Confidentialité & Sécurité',
    language: 'Langue & Traduction',
    appearance: 'Apparence & Thèmes',
    storage: 'Données & Stockage',
    devices: 'Appareils & Sessions',
    help: 'Aide & FAQ',
    myAccount: 'Mon Compte',
    general: 'Général',
    account: 'Compte',
    inbox: 'Boîte de réception',
    sent: 'Envoyés',
    drafts: 'Brouillons',
    trash: 'Corbeille',
    starred: 'Favoris',
    archive: 'Archives',
    newChat: 'Nouveau Chat',
    newGroup: 'Nouveau Groupe',
    newChannel: 'Nouvelle Chaîne',
    newMail: 'Rédiger un e-mail',
    voiceCall: 'Appel Vocal',
    videoCall: 'Appel Vidéo',
    languageSettingsDesc: 'Choisissez la langue de l\'interface et les paramètres de traduction des messages.',
  },
  de: { // German
    chats: 'Chats',
    groups: 'Gruppen',
    channels: 'Kanäle',
    communities: 'Communitys',
    mail: 'E-Mail',
    stories: 'Stories',
    settings: 'Einstellungen',
    search: 'Suchen...',
    typeMessage: 'Nachricht schreiben...',
    savedMessages: 'Gespeicherte Nachrichten',
    interfaceLanguage: 'App-Sprache',
    translationTarget: 'Zielübersetzungssprache',
    searchLanguage: 'Sprache suchen...',
    autoTranslate: 'Nachrichten automatisch übersetzen',
    autoTranslateDesc: 'Eingehende Nachrichten automatisch in Ihre Zielsprache übersetzen',
    online: 'online',
    offline: 'offline',
    translating: 'Übersetzen...',
    showOriginal: 'Original anzeigen',
    showTranslation: 'Übersetzung anzeigen',
    editProfile: 'Profil bearbeiten',
    notifications: 'Mitteilungen & Töne',
    privacy: 'Datenschutz & Sicherheit',
    language: 'Sprache & Übersetzung',
    appearance: 'Erscheinungsbild & Designs',
    storage: 'Daten & Speicher',
    devices: 'Geräte & Sitzungen',
    help: 'Hilfe & FAQ',
    myAccount: 'Mein Konto',
    general: 'Allgemein',
    account: 'Konto',
    inbox: 'Posteingang',
    sent: 'Gesendet',
    drafts: 'Entwürfe',
    trash: 'Papierkorb',
    starred: 'Markiert',
    archive: 'Archiv',
    newChat: 'Neuer Chat',
    newGroup: 'Neue Gruppe',
    newChannel: 'Neuer Kanal',
    newMail: 'E-Mail verfassen',
    voiceCall: 'Sprachanruf',
    videoCall: 'Videoanruf',
    languageSettingsDesc: 'Wählen Sie die Sprache der Benutzeroberfläche und die Einstellungen für die Nachrichtenübersetzung.',
  },
  zh: { // Chinese
    chats: '聊天',
    groups: '群组',
    channels: '频道',
    communities: '社区',
    mail: '邮件',
    stories: '动态',
    settings: '设置',
    search: '搜索...',
    typeMessage: '输入消息...',
    savedMessages: '收藏消息',
    interfaceLanguage: '界面语言',
    translationTarget: '默认翻译目标语言',
    searchLanguage: '搜索语言...',
    autoTranslate: '自动翻译接收到的消息',
    autoTranslateDesc: '自动将收到的消息翻译为您的目标语言',
    online: '在线',
    offline: '离线',
    translating: '翻译中...',
    showOriginal: '显示原文',
    showTranslation: '显示译文',
    editProfile: '编辑个人资料',
    notifications: '通知与声音',
    privacy: '隐私与安全',
    language: '语言与翻译',
    appearance: '外观与主题',
    storage: '数据与存储',
    devices: '设备与会话',
    help: '帮助与常见问题',
    myAccount: '我的账户',
    general: '常规',
    account: '账户',
    inbox: '收件箱',
    sent: '已发送',
    drafts: '草稿',
    trash: '回收站',
    starred: '已星标',
    archive: '归档',
    newChat: '新建聊天',
    newGroup: '新建群组',
    newChannel: '新建频道',
    newMail: '撰写邮件',
    voiceCall: '语音通话',
    videoCall: '视频通话',
    languageSettingsDesc: '选择应用界面显示语言和消息翻译偏好。',
  },
  ar: { // Arabic
    chats: 'المحادثات',
    groups: 'المجموعات',
    channels: 'القنوات',
    communities: 'المجتمعات',
    mail: 'البريد',
    stories: 'القصص',
    settings: 'الإعدادات',
    search: 'بحث...',
    typeMessage: 'اكتب رسالة...',
    savedMessages: 'الرسائل المحفوظة',
    interfaceLanguage: 'لغة التطبيق',
    translationTarget: 'لغة الترجمة',
    searchLanguage: 'البحث عن لغة...',
    autoTranslate: 'ترجمة الرسائل القادمة تلقائياً',
    autoTranslateDesc: 'ترجمة الرسائل الواردة تلقائياً إلى لغتك المفضلة',
    online: 'متصل',
    offline: 'غير متصل',
    translating: 'جاري الترجمة...',
    showOriginal: 'إظهار الأصل',
    showTranslation: 'إظهار الترجمة',
    editProfile: 'تعديل الملف الشخصي',
    notifications: 'الإشعارات والأصوات',
    privacy: 'الخصوصية والأمان',
    language: 'اللغة والترجمة',
    appearance: 'المظهر والسمات',
    storage: 'البيانات والتخزين',
    devices: 'الأجهزة والجلسات',
    help: 'المساعدة والأسئلة الشائعة',
    myAccount: 'حسابي',
    general: 'عام',
    account: 'الحساب',
    inbox: 'البريد الوارد',
    sent: 'المرسل',
    drafts: 'المسودات',
    trash: 'سلة المهملات',
    starred: 'المميزة بنجمة',
    archive: 'الأرشيف',
    newChat: 'محادثة جديدة',
    newGroup: 'مجموعة جديدة',
    newChannel: 'قناة جديدة',
    newMail: 'إنشاء بريد',
    voiceCall: 'مكالمة صوتية',
    videoCall: 'مكالمة فيديو',
    languageSettingsDesc: 'اختر لغة واجهة التطبيق وإعدادات ترجمة الرسائل.',
  },
};

export function getUIText(key: string, langCode: string = 'en'): string {
  const dict = UI_DICTIONARY[langCode] || UI_DICTIONARY['en'];
  if (dict && dict[key]) {
    return dict[key];
  }
  if (UI_DICTIONARY['en'] && UI_DICTIONARY['en'][key]) {
    return UI_DICTIONARY['en'][key];
  }
  return key;
}

const translationCache = new Map<string, { text: string; detectedSource: string; engine: string }>();

export async function translateText(
  text: string,
  targetLang: string,
  sourceLang: string = 'auto'
): Promise<{ text: string; detectedSource: string; engine: string }> {
  if (!text || !text.trim()) {
    return { text: '', detectedSource: 'auto', engine: '' };
  }

  const cacheKey = `${text.trim()}__${sourceLang}__${targetLang}`;
  if (translationCache.has(cacheKey)) {
    return translationCache.get(cacheKey)!;
  }

  // Attempt 1: Google Client Translate API
  try {
    const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=${sourceLang}&tl=${targetLang}&dt=t&q=${encodeURIComponent(text)}`;
    const res = await fetch(url);
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data) && Array.isArray(data[0])) {
        const translatedParts = data[0].map((part: any) => part[0]).filter(Boolean);
        const translatedResult = translatedParts.join('');
        const detectedSrc = data[2] || 'auto';
        if (translatedResult && translatedResult.trim()) {
          const outcome = {
            text: translatedResult,
            detectedSource: detectedSrc,
            engine: 'Neural Engine',
          };
          translationCache.set(cacheKey, outcome);
          return outcome;
        }
      }
    }
  } catch (err) {
    console.warn('Google Client Translate API failed, trying fallback...', err);
  }

  // Attempt 2: MyMemory Translation API fallback
  try {
    const langPair = `${sourceLang === 'auto' ? 'autodetect' : sourceLang}|${targetLang}`;
    const url = `https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${langPair}`;
    const res = await fetch(url);
    if (res.ok) {
      const data = await res.json();
      if (data && data.responseData && data.responseData.translatedText) {
        const translatedResult = data.responseData.translatedText;
        const outcome = {
          text: translatedResult,
          detectedSource: data.responseData.detectedLanguage || 'auto',
          engine: 'Neural Engine',
        };
        translationCache.set(cacheKey, outcome);
        return outcome;
      }
    }
  } catch (err) {
    console.warn('MyMemory Translate API failed', err);
  }

  // Fallback: If network fails or offline
  const fallbackOutcome = {
    text: `[Translated to ${targetLang.toUpperCase()}]: ${text}`,
    detectedSource: 'auto',
    engine: 'Offline Translation',
  };
  return fallbackOutcome;
}
